// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpGkcmfkKekROISkDDNdu8OXrt7FZGodo',
    appId: '1:95925469489:android:06ec730e8944dae951f010',
    messagingSenderId: '95925469489',
    projectId: 'lifehack22environment',
    databaseURL: 'https://lifehack22environment-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lifehack22environment.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdq8ka4YbCYAQiQ00CRCVK2XFBiTcHLto',
    appId: '1:95925469489:ios:1ce76f97e12cbd5e51f010',
    messagingSenderId: '95925469489',
    projectId: 'lifehack22environment',
    databaseURL: 'https://lifehack22environment-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lifehack22environment.appspot.com',
    iosClientId: '95925469489-aig7k5c50m0924vffbo6j07k4kba973r.apps.googleusercontent.com',
    iosBundleId: 'com.example.lifehackApp',
  );
}
